# Generated by Django 2.2.3 on 2019-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahuweb', '0002_auto_20190812_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
