# Generated by Django 2.2.3 on 2019-08-14 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sahuweb', '0004_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='track',
            field=models.FileField(default=django.utils.timezone.now, upload_to='album'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
